
CREATE TABLE public.team_data (
 id integer NOT NULL,
 name varchar(100) NOT NULL,
 link varchar(100) NOT NULL,
 abbreviation varchar(10) NOT NULL,
 teamName varchar(100) NOT NULL,
 locationName varchar(100) NOT NULL,
 firstYearOfPlay varchar(4) NOT NULL,
 shortName varchar(25) NOT NULL,
officialSiteUrl varchar(100) NOT NULL,
franchiseId integer NOT NULL,
active boolean NULL,
venue_name varchar(100) NULL,
venue_link varchar(100) NULL,
venue_city varchar(100) NULL,
venue_timeZone_id varchar(25) NULL,
venue_timeZone_offset integer NULL,
venue_timeZone_tz varchar(25) NULL,
division_id integer NULL,
division_name varchar(100) NULL,
division_nameShort varchar(25) NULL,
division_link varchar(100) NULL,
division_abbreviation varchar(10) NULL,
conference_id integer NULL,
conference_name varchar(100) NULL,
conference_link varchar(100) NULL,
francise_franciseId integer NULL,
franchise_teamName varchar(100) NULL,
franchise_link varchar(100) NULL,
)
